config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  	resources :dashboard

	resources :companies do
		resources	:gigs do
			resource :proposals, except: :index
		end
		# resources	:proposals
	end
	resources	:gigs
	# Manage links to interns, resumes
	resources :resumes do
		resources :edus
		resources :jobs
		resources :skills

	end
 
 # if user_signed_in? && current_user.is_employer?
		root 'gigs#index'
	# else 
		root 'gig#resumes'
	# end
		get 'listing' => "companies#listing"

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many	:categories
	has_many	:gigs
	belongs_to	:user
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :set_company, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index]

def listing
	@company = Company.where(user_id: current_user.id)
	@gigs = Gig.all
end

def index
	@company = Company.all
	@gig = Gig.all.order("created_at DESC")
end

def new
	@company = Company.new
end

def create
	@company = Company.new (company_params)
	@company.user_id = current_user.id
	@company.save!
	redirect_to @company	
end

def show
	@gigs = Gig.where(company_id: @company.id).order("created_at DESC")
end

def edit
	
end

def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
	@company.destroy
	redirect_to @company
end


private 


	def company_params
		params.require(:company).permit(:cname, :industry, :email, :website, :location, :description)
	end

	def check_user
      unless (@company.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this company belongs to someone else, you can only edit companies you have posted."
      end
    end

	def set_company
		@company = Company.find_by(:id => params[:id])	
	end


end

app/views/companies/_form.html.erb
<div class="container">

<div class="col-sm-8">
			<%= form_for @company do |f| %>
    	<div class= "row"> 
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Company %>
                    <%= f.text_field :cname, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
                <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Industry %>
                    <%= f.text_field :industry, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
            <div class="col-sm-5">
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>

            <div class="col-sm-5">
                <div class="form-group">
                    <%= f.label :website %>
                    <%= f.text_field :website, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Location %>
                    <%= f.text_field :location, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
             <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :About_us %>
                    <%= f.text_area :description, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>


    		
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                 <%= f.submit "Submit ", class: "btn btn-secondary btn-block" %>
                </div>
            </div>

        </div>
        <%end%>
    </div>

app/views/companies/edit.html.erb
<div class="container">

<h4 class ="center">Edit company details</h4>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company, class: "btn btn-link" %> |
<%= link_to 'Back', listing_path, class: "btn btn-link"  %>

</div>

app/views/companies/index.html.erb
 <div class="container">
    <div class="row">
    <div class="col-sm-9">
        <!--Either display companies by the current user logged in or all companies -->

<% if user_signed_in? && current_user.is_employer? %> 
    <div class="companies-list">
        <% if @companies.blank? %>
            <p> You do not have a company to post internships, <%= link_to "Create a New Company", new_company_path, class: "primary" %>
        <% else %>
        <h2 class="page-header">My Companies</h2>
            <p class="small">Employer, Select one of your Companies or subsidiary to post an Internship position, or <%= link_to "Create a New Company", new_company_path %> </p>
        <% end %>

            <% @companies.each do |company| %> 
                <div class="companies-list-item">
                    <div class="companies-list-item-image">
                        (logo)
                    </div><!-- /.companies-list-item-image -->

                    <div class="companies-list-item-heading">
                        <h2><%= link_to company.cname, company %></h2>
                        <h3><%= company.location %></h3>
                    </div><!-- /.companies-list-item-heading -->

                    <div class="companies-list-item-count">
                        <a href="#">4 open positions</a>
                        
                    </div><!-- /.positions-list-item-count -->

                    <div class="companies-list-item-rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <p class="count"> Interns</p>
                        <span class="companies-list-item-rating-count">53</span>
                         <span class="pcompanies-list-item-rating-count"><%= link_to "Delete", company, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                    </div><!-- /.companies-list-item-rating -->
                </div><!-- /.companies-list-item -->
            <% end %>
        </div><!-- /.companies-list -->
    <% end %>
    

        <h2 class="page-header">Displaying <strong class="red"><%= Company.count %></strong> Companies that are hiring Interns</h2>


        <div class="companies-list">
            <% @company.each do |company| %> 
                <div class="companies-list-item">
                    <div class="companies-list-item-image">
                        (logo)
                    </div><!-- /.companies-list-item-image -->

                    <div class="companies-list-item-heading">
                        <h2><%= link_to company.cname, company %></h2>
                        <h3><%= company.location %></h3>
                    </div><!-- /.companies-list-item-heading -->

                    <div class="companies-list-item-count">
                        <a href="#">4 open positions</a>
                    </div><!-- /.positions-list-item-count -->

                    <div class="companies-list-item-rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <p class="count"> Interns</p>
                        <span class="companies-list-item-rating-count">53</span>
                         <span class="pcompanies-list-item-rating-count"><%= link_to "Delete", company, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                    </div><!-- /.companies-list-item-rating -->
                </div><!-- /.companies-list-item -->
            <% end %>

        </div><!-- /.companies-list -->



<!-- <div class="center">
    <ul class="pagination">
        <li>
            <a href="#">
                <i class="fa fa-chevron-left"></i>
            </a>
        </li>

        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li class="active"><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
            <a href="#">
                <i class="fa fa-chevron-right"></i>
            </a>
        </li>
    </ul>
  </div> --><!-- /.center -->
    </div><!-- /.col-* -->

    <div class="sidebar col-sm-3">
        <h2>Open Positions</h2>

        <div class="positions-list-small">
            <div class="positions-list-small-item">
                <h2><a href="#">UX/UI Senior Designer</a></h2>
                <h3><span>(logo))</span> Dropbox Inc. <br>San Francisco, California</h3>
            </div>
        </div><!-- /.positions-list-small -->
    </div><!-- /.col-* -->
</div><!-- /.row -->

</div><!-- /.container -->

app/views/companies/listing.html.erb
  <div class="container">
    <div class="row">
    <div class="col-sm-12">
   <h2 class="page-header">Dashboard</h2>
        <% if @company.blank? %>
        <p> You do not have any company or organisation, <%= link_to "Create a new Company".html_safe, new_company_path %> to hire an Intern  </p>
        <% else %>
        <p> Select one of your companies below to view or <B> post an internship</B> oportunity or <%= link_to "Create a new Company".html_safe, new_company_path %> </p>
        <%end%>
            
        <div class="companies-list">
            <hr>
            <h4>My Companies</h4>
            <% @company.each do |company| %> 
                <div class="companies-list-item">
                    <div class="companies-list-item-image">
                        (logo)
                    </div><!-- /.companies-list-item-image -->

                     <div class="companies-list-item-heading">
                        <h2><%= link_to company.cname, company %></h2>
                          <span class="small"><%= link_to "Update Company", edit_company_path(company) %></span>
                    </div><!-- /.companies-list-item-heading -->


                    <div class="companies-list-item-heading">

                    <h3><%= company.location %></h3>
                    </div><!-- /.companies-list-item-heading -->
                    
                    <div class="companies-list-item-count">
                        <span><%= link_to "#{@gigs.length} open positions", company %> </span><br>
                         
                    </div><!-- /.positions-list-item-count -->

                    <div class="companies-list-item-rating">
                        <%= link_to "Post an Internship".html_safe, new_company_gig_path(company), class: "btn btn-secondary" %> <br>
                       
                    </div><!-- /.companies-list-item-rating -->
                </div><!-- /.companies-list-item -->
            <% end %>

        </div><!-- /.companies-list -->

        <!-- Display a list of all the gigs for this users, status, budget, applications received, delete & update -->

    
 <div class="center">
    <ul class="pagination">
        <li>
            <a href="#">
                <i class="fa fa-chevron-left"></i>
            </a>
        </li>

        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li class="active"><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
            <a href="#">
                <i class="fa fa-chevron-right"></i>
            </a>
        </li>
    </ul>
  </div><!-- /.center -->
    </div><!-- /.col-* -->

</div><!-- /.row -->

</div><!-- /.container -->

app/views/companies/new.html.erb
<div class="container">
	<h4 class ="center">Create a company </h4>
    <div class="col-sm-8">
			<%= form_for @company do |f| %>
    	<div class= "row"> 
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Company %>
                    <%= f.text_field :cname, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
                <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Industry %>
                    <%= f.text_field :industry, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
            <div class="col-sm-5">
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>

            <div class="col-sm-5">
                <div class="form-group">
                    <%= f.label :website %>
                    <%= f.text_field :website, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Location %>
                    <%= f.text_field :location, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>
             <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :About_us %>
                    <%= f.text_area :description, class: "form-control input-lg" %>
                    <small class="healer block"> Only verified employers can see this</small>
                </div><!-- /.form-group -->
            </div>


    		
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                 <%= f.submit "Add + ", class: "btn btn-secondary btn-block" %>
                </div>
            </div>

	</div>
		<% end %>

</div><!-- /.col-* -->

app/views/companies/show.html.erb
<div class="container">
    <div class="row">
                        <p><%= link_to '&larr; Back to my companies'.html_safe, listing_path, class: "btn btn-link"  %></p>
        <div class="col-sm-4">
          <div class="company-card">
            <div class="company-card-image">
                <span><%= @company.cname%> Card</span>
            </div><!-- /.company-card-image -->
                <div class="company-card-data">
                    <dl>
                       
                        <dt>E-mail</dt>
                        <dd><%= @company.email %></dd>

                         <dt>Website</dt>
                        <dd><%= @company.website %></dd>

                      <!--   <dt>Phone</dt>
                        <dd>coming soonn</dd>
 -->
                        <dt>Location</dt>
                        <dd><%= @company.location %></dd>
                    </dl>

                </div><!-- /.company-card-data -->
        </div><!-- /.company-card -->


            <div class="widget">

                <h3 class="page-header">Company Profile</h3>

            <p><%= @company.description %></p>

            <span class="small"><%= link_to "Delete this company", company_path(@company), method: :delete %> </span>

            </div><!-- /.widget -->

          
        </div><!-- /.col-* -->

        <div class="col-sm-8">
            <div class="company-header">
              

                <h1><%= @company.cname%><span>industry</span></h1>




                <%= link_to "Post an Internship".html_safe, new_company_gig_path(@company), class: "btn btn-secondary" %>
            </div><!-- /.company-header -->

            <div class="company-stats">
                <div class="company-stat">
                    <span>Positions</span>
                    <strong><%= "#{@company.gigs.length}" %></strong>
                </div><!-- /.company-stat -->

                <div class="company-stat">
                    <span>Applications</span>
                    <strong>43</strong>
                </div><!-- /.company-stat -->

                <div class="company-stat">
                    <span>Interviewed</span>
                    <strong>324</strong>
                </div><!-- /.company-stat -->
            </div><!-- /.company-stat -->
               
            <h3 class="page-header">Open Positions</h3>

            <div class="positions-list">
                    <% @gigs.each do |gig| %> 
                <div class="positions-list-item">
                    <h2><%= link_to gig.name, company_gig_path(@company, gig) %></h2>
                    <h3><%= gig.location %><br></h3>

                        <p><%= gig.description %></p>
                        <Span class="small">Duration:<b> <%= gig.duration %> Months </b></span>
                            <span class="small"> Starting on: <b><%= gig.startdate %></b><br>
                         <span class="small"><%= link_to "Update", edit_company_gig_path(@company, gig) %></span> or <span class="small"><%= link_to "Delete", company_gig_path(@company, gig), method: :delete %> </span>


                    <div class="position-list-item-date"> <small = "small ">Posted: <%= time_ago_in_words(gig.created_at) %> ago</div><!-- /.position-list-item-date -->

                   <!--  <span class="position-list-item-action">Number of applicants<br> -->
                       


                    </div><!-- /.position-list-item-action -->
                <% end %>
                    </div><!-- /.positions-list-item -->
            </div><!-- /.positions-list -->
        </div><!-- /.col-sm-8 -->
    </div><!-- /.row -->
</div><!-- /.container -->