config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  	resources :dashboard

	resources :companies do
		resources	:gigs do
			resource :proposals, except: :index
		end
		# resources	:proposals
	end
	resources	:gigs
	# Manage links to interns, resumes
	resources :resumes do
		resources :edus
		resources :jobs
		resources :skills

	end
 
 # if user_signed_in? && current_user.is_employer?
		root 'gigs#index'
	# else 
		root 'gig#resumes'
	# end
		get 'listing' => "companies#listing"

end

app/models/gig.rb
class Gig < ActiveRecord::Base
	belongs_to	:company
	has_many	:proposals
	belongs_to 	:category
	has_many	:abilities
	has_many	:skills, through: :abilities

	validates :name, :description, :budget, :startdate, :duration, presence: true

	def skill_list=(skills_string)
		skill_names = skills_string.split(",").collect{ |s| s.strip.downcase}.uniq
		new_or_found_skills = skill_names.collect { |name| Skill.find_or_create_by(name: name) }
		self.skills = new_or_found_skills
	end

	def skill_list
		self.skills.collect do |skill|
			skill.name
		end.join(",")
	end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
	 before_action :set_company, except: [:index, :show, :update]
	 before_action :set_gig, only: [:show, :edit, :update, :destroy]
	 # before_action :authenticate_user!, except: [:index]

	def index
		@gig = Gig.all
	end

	def new
		@gig = Gig.new 
	end

	def create
		@gig = Gig.new(gig_params)
		@gig.company_id = @company.id
		@gig.save!
		redirect_to @company
	end

	def show
		@gig = Gig.find(params[:id])
		@company = Company.where(gig_id: @gig.id)
		@proposal = @gig.proposals.order("created_at DESC")
		# @resume = @user.resumes.order("created_at DESC")
		@resume = Resume.all
		#@resumes = Resume.where(user_id: @user.id).order("created_at DESC")
		@awarded_internship = Proposal.where(id: @gig.awarded_internship).first
	end


	def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

	def destroy
		@gig.destroy
		redirect_to company_path(@company)
	end


	
#private stuff
	private

	def set_company
		@company = Company.find(params[:company_id])	
	end

	def set_gig
		@gig = Gig.find_by(:id => params[:id])
	end

	def gig_params
		params.require(:gig).permit(:name, :description, :budget, :startdate, :duration, :location, :category_id, :skill_list, :awarded_internship)
	end




end

app/views/gigs/_form.html.erb
<div class="container">
	<h3 class ="center">Post an Internship Opportunity For <%= @company.cname%> </h3>
	<br>
    <div class="col-sm-8">
<%= form_for([@company, @gig ]) do |f| %>   

<!-- error control -->



    	<div class= "row"> 
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :Position %>
    				<%= f.text_field :name, autofocus: true, class: "form-control input-lg" %>
    			</div><!-- /.form-group -->
                
    		</div> 
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :category_id %>
                    <small>We will use category to match you to the right interns</small>
                    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { }, class: "form-control " %>
                </div><!-- /.form-group -->
                
            </div>
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :description %>
                    <small>Be as descriptive as possible about the work </small>
    				<%= f.text_area :description, class: "form-control" %>
    			</div><!-- /.form-group -->
    		</div>
            <div class="col-sm-10">
               
                <div class="form-group">
                    <%= f.label :skills %>
                     <small>required for this internship, separate with commas i.e Ms Word, Excel</small>
                    <%= f.text_area :skill_list, rows: 3,  class: "form-control" %>
                </div><!-- /.form-group -->
                 
            </div>
           
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :location %>
                    <small>Where will the intern work from?</small>
    				<%= f.text_field :location, class: "form-control " %>
    			</div><!-- /.form-group -->
    		</div>


            <div class="col-sm-4">
                <div class="form-group">
                    <%= f.label :stipend %>
                    <div class="input-group">
                      <div class="input-group-addon">Kshs</div>
                      <%= f.number_field :budget, :min => 5000, class: "form-control" %>
                        </div>
                    
                </div><!-- /.form-group -->
            </div>

            <div class="col-sm-2">

                <div class="form-group">
                    <%= f.label :Months %> <br>
                    <%= f.select :duration, (0..6),  class: "form-control input-lg" %>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <%= f.label :Start_Date %> 
                    <%= f.date_field :startdate, min: Date.today+2, class: "form-control" %>
                </div><!-- /.form-group -->
            </div>
            
    		<div class="col-sm-10">
  			<div class="form-group">
             <!-- <button type="submit" class="btn btn-secondary btn-block">   <%= f.submit "Sign up" %> </button> -->
             <%= f.submit "Post the Opportunity", class: "btn btn-secondary btn-block" %>
            </div>

            
        </div>
		</div>
		<% end %>
    </div><!-- /.col-* -->

    <div class="col-sm-4">
    	<div class="widget">
            <h2>How it works</h2>
            <p>Post an appealing position in your company to attract smart interns, you will find listed candidates on your dashboard </p>
            <p>Describe the position and skilled requireds in detail, add a start date and a stipend, atleast a minimum of Kshs 5000 to cover their overheads</p>
            <p>A list of applicants will appear on your listing.</p>
        </div><!-- /.widget -->
      
        <div class="widget">
            <h2>Make sure to Include</h2>
            <ul class="nav">
                <li><a href="#"><span>1.</span> Describe of work</a></li>
                <li><a href="#"><span>2.</span> Months: Duration of internship</a></li>
                <li><a href="#"><span>3.</span> Stipend: Basic pay, min 5000</a></li>
                <li><a href="#"><span>4.</span> Skills required</a></li>
                <!-- <li><a href="#"><span>5.</span> Mentorship Opportunities </a></li> -->
            </ul>
        </div><!-- /.widget -->    
    </div><!-- /.col-* -->
</div><!-- /.container -->

app/views/gigs/edit.html.erb
<div class="container">

<h4 class ="center">Edit gig details</h4>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company, class: "btn btn-link" %> |
<%= link_to 'Back', listing_path, class: "btn btn-link"  %>

</div>

app/views/gigs/index.html.erb
<div class="container">
    <h2 class="page-header">Displaying <strong class="red"><%= Gig.count %></strong> internship position available for you </h2>
    <p>Select an internship opportunity below and apply </p>
     <div class="companies-list">   
     <% @gig.each do |gig| %>        
              <div class="companies-list-item">
                    <div class="companies-list-item-image">
                       Logo
                    </div><!-- /.companies-list-item-image -->

                <div class="companies-list-item-heading col-sm-4">
                 
                    <h2><%= link_to gig.name, gig %> </h2>
                     <small = "small ">Posted: <%= time_ago_in_words(gig.created_at) %> ago</small><br>
                    <!-- <small><%= gig.category %></small><br> -->
                    <!-- <h2>Company name </h2>  -->
                    <small><%= gig.description %></Small>          
                </div><!-- /.companies-list-item-heading -->
                <div class="companies-list-item-count">
                        <h2><span class="label label-info large">Pay: <%= gig.budget %> /=</span></h2>
                         <small>Duration: <%= gig.duration %> Months</small><br>
                      <!-- <span>Starts: <%= gig.startdate.strftime (" %d - %b - %Y") %></a></span><br> -->
                      <small>Location: <%= gig.location %></Small>
                </div><!-- /.positions-list-item-count -->

                <div class="companies-list-item-rating">
                       <small>Starts: <%= gig.startdate.strftime (" %d - %b - %Y") %></a></small><br>
                       <ul class="header-actions nav nav-pills">
                        <li><%= link_to "Apply Now", gig_path(gig), class: "primary" %>
                        </ul>
                        <!-- <span class="companies-list-item-rating-count">/ 53</span> -->
                </div><!-- /.companies-list-item-rating -->
              </div><!-- /.companies-list-item -->
            <% end %>
        <div class="center">
          <ul class="pagination"> 
            <li></li>
            <li><a href="#">2</a></li>
            <li class="active"><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
          </ul>
      </div>
</div> <!-- page wrapper -->

app/views/gigs/new.html.erb
<div class="container">
	<h4 class ="center">Post an Internship Opportunity</h4>
	<br>
    <div class="col-sm-8">
<%= form_for([@company, @gig ]) do |f| %>    
    	<div class= "row"> 

    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :Position %>
    				<%= f.text_field :name, autofocus: true, class: "form-control input-lg" %>
    			</div><!-- /.form-group -->
                
    		</div> 
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :category_id %>
                    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { }, class: "form-control " %>
                </div><!-- /.form-group -->
                
            </div>
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :description %>
    				<%= f.text_area :description, class: "form-control" %>
    			</div><!-- /.form-group -->
    		</div>
            <div class="col-sm-10">
               
                <div class="form-group">
                    <%= f.label :skills %>
                     <small>required for this internship</small>
                    <%= f.text_area :skill_list, rows: 3,  class: "form-control" %>
                </div><!-- /.form-group -->
                 
            </div>
           
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :location %>
    				<%= f.text_field :location, class: "form-control " %>
    				
    			</div><!-- /.form-group -->
    		</div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= f.label :stipend %>
                    <div class="input-group">
                      <div class="input-group-addon">Kshs</div>
                      <%= f.number_field :budget, class: "form-control" %>
                        </div>
                    
                </div><!-- /.form-group -->
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= f.label :duration %>
                    <%= f.number_field :duration, class: "form-control" %>
                    
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <%= f.label :startdate %>
                    <%= f.date_field :startdate, class: "form-control" %>
                </div><!-- /.form-group -->
            </div>
            
    		<div class="col-sm-10">
  			<div class="form-group">
             <!-- <button type="submit" class="btn btn-secondary btn-block">   <%= f.submit "Sign up" %> </button> -->
             <%= f.submit "Post the Opportunity", class: "btn btn-secondary btn-block" %>
            </div>

            
        </div>
		</div>
		<% end %>
    </div><!-- /.col-* -->

    <div class="col-sm-4">
    	<div class="widget">
            <h2>How it works</h2>
            <p>Looking for interns? Get your Company account in one min here <%= link_to "Create Account", new_user_registration_path %> </p>
            <p>Post an appealing position in your company to attract smart interns to apply, you will find listed candidates on your dashboard </p>
        </div><!-- /.widget -->
      
        <div class="widget">
            <h2>Make sure to Include</h2>
            <ul class="nav">
                <li><a href="#"><span>1.</span> Internship Opportunity</a></li>
                <li><a href="#"><span>2.</span> Duration of internship</a></li>
                <li><a href="#"><span>3.</span> Basic pay or stipend</a></li>
                <li><a href="#"><span>4.</span> Experience or Education</a></li>
                <li><a href="#"><span>5.</span> Mentorship Opportunities </a></li>
            </ul>
        </div><!-- /.widget -->    
    </div><!-- /.col-* -->
</div><!-- /.container -->

app/views/gigs/show.html.erb
<div class="container">
        <div class="main">
            <!-- <div class="document-title"> -->
                 <div class="position-header">
					<h1> <%= @gig.name %> <span class="label label-success"><%= @gig.budget %></span></h1>
					<small>Created on <%= @gig.created_at.strftime (" %d of %b %Y") %></small><br>
					<small><%= @gig.location %> </small>

					<!-- <h2><span class="position-header-company-image"></span><%= link_to @company.name %>	</h2> -->
					
				</div><!-- /.position-header -->
	<div class="row">
		<h3 class="page-header">Description, skills, responsibilities</h3>
			<div class="col-sm-8">
					<p>
						<%= @gig.description %> 
					</p>

				<h3 class="page-header">Skills</h3>
					<% @gig.skills.each do | skill | %>
						<ul>
							<li><%= skill.name %></li>
						</ul>

					<% end %>

		<h3 class="page-header">  Invited for interviews or hired </span> </h3>
	<div class="companies-list">
			<% if @awarded_internship.blank? %>

			<p>Internship is still open</p>
			<% else %>

				<div class="companies-list-item">
	                 <!--    <div class="companies-list-item-image">
	                        A
	                    </div>-->

	                    <div class="companies-list-item-heading">
	                        <h2><%= @awarded_internship.user.name %></h2>
	                        <h3>Category</h3>
	                        <small>Applied: <%= time_ago_in_words(@awarded_internship.created_at) %> ago</small>


	                    </div><!-- /.companies-list-item-heading -->

	                    <div class="companies-list-item-count">
	                    	<h3>Application </h3>
	                        <span><%= @awarded_internship.description %></span><br>
	                    </div><!-- /.positions-list-item-count -->
	                </div><!-- /.companies-list-item -->
			<% end %>

			<h3 class="page-header">  Applications received so far: <span class="label label-info"><%= "#{@proposal.length}" %></span> </h3>
		<div class="companies-list">

				<% @gig.proposals.each do |proposal| %>
	                <div class="companies-list-item">
	                 <!--    <div class="companies-list-item-image">
	                        A
	                    </div>-->
	                    <div class="companies-list-item-heading">
	                        <h2><%= proposal.user.name %></h2>
	                        <h3>Category</h3>
	                        <small>Applied: <%= time_ago_in_words(proposal.created_at) %> ago</small>


	                    </div><!-- /.companies-list-item-heading -->

	                    <div class="companies-list-item-count">
	                    	<h3>My Introduction </h3>
	                        <span><%= proposal.description %></span><br>
	                    </div><!-- /.positions-list-item-count -->

	                    <div class="companies-list-item-rating">
						<% if user_signed_in? %>
						<% @resume.each do |resume| %>
	                         <span class= "form-control" ><%= link_to resume.user.name, resume %></span><br>   
	                         <% end %>
	                       <!-- Only Gig owners should see this -->

		                         <%= form_for @gig, method: :put do |f| %>
		                         <%= f.hidden_field :awarded_internship, value: proposal.id %>
		                         <%= f.hidden_field :open, value: false %>
		                         <%= f.submit "Invite for Interview", class: "btn" %>

	                         <% end %>
	                         <% end %>
	             
	         			</div><!-- /.companies-list-item-rating -->
	         	
	                </div><!-- /.companies-list-item -->
	             
	             <% end %>
        </div><!-- /.companies-list -->
		</div><!-- /.col-* -->

</div>

<div class="col-sm-4">
	<div class="position-general-information">
				<dl>
					<dt>Status</dt>
					<dd><%= @gig.open %> </dd>

					<dt>Duration</dt>
					<dd><%= @gig.duration %> Months </dd>

					<dt>Stipend</dt>
					<dd><%= @gig.budget %>/= (pm)</dd>

					<dt>Start Date</dt>
					<dd><%= @gig.startdate.strftime (" %d - %b - %Y") %> </dd>

				</dl>
			</div><br><!-- /.position-general-information -->

			<div class="widget">
			
				<h2>Apply for this Internship</h2>
				<%= form_for :proposals, url: company_gig_proposals_path(@company, @gig) do |f| %>
					<div class="form-group">
                        <%= f.label :Introduce_yourself %>
                        <%= f.text_area :description, rows: 5,  class: "form-control" %>
                    </div><!-- /.form-group -->
               		<%=f.submit "Submit Application", class: "btn btn-secondary pull-right" %>
			
			<% end %>
			</div><!-- /.widget -->
		</div><!-- /.col-* -->

	</div><!-- /.row -->
</div><!-- /.container -->

</div><!-- /.main -->
</div><!-- /.main-wrapper -->