config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  	resources :dashboard

	resources :companies do
		resources	:gigs do
			resource :proposals, except: :index
		end
		# resources	:proposals
	end
	resources	:gigs
	# Manage links to interns, resumes
	resources :resumes do
		resources :edus
		resources :jobs
		resources :skills

	end
 
 # if user_signed_in? && current_user.is_employer?
		root 'gigs#index'
	# else 
		root 'gig#resumes'
	# end
		get 'listing' => "companies#listing"

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	#belongs_to :category
	has_many :proposals
	belongs_to	:user 
	has_many	:edus
	has_many	:jobs
	has_many	:skills
	has_many	:abilities
	has_many	:skills, through: :abilities
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	before_action :set_resume, only: [:index, :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		@resume = Resume.all
	end

	def new
		@resume = Resume.new	
	end

	def create
		@resume = Resume.new (resume_params)
		@resume.user_id = current_user.id
		@resume.save!
		redirect_to @resume
	end

	def show
		@resume = Resume.find(params[:id])
		@jobs = Job.where(resume_id: @resume.id)
		@edus = Edu.where(resume_id: @resume.id)
		@skills = Skill.where(resume_id: @resume.id)

	end

	def destroy
		@resume.destroy
		redirect_to @resume	
	end

private

	def resume_params
		params.require(:resume).permit(:fname, :lname, :age, :phone, :address, :category, :bio)
	end

	def set_resume
		
	end

end

app/views/resumes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-9">
			<h2 class="page-header"><strong><%= Resume.count %></strong> candidates looking for attachments</h2>

			<div class="candidates-list">
	           <% @resume.each do |resume| %>
        	<div class="candidates-list-item">
                <div class="candidates-list-item-heading">
            		<div class="candidates-list-item-image">
            			<!-- <a href="#">
            				<img src="assets/img/tmp/resume.jpg" alt="Elliot Sarah Scott">
            			</a> -->

                        
                            <!-- <a href="#" class="candidates-list-item-image-label">
                                <img src="assets/img/tmp/instagram.png" alt="">
                            </a>    -->                 
                        
            		</div><!-- /.candidates-list-item-image -->

                    <div class="candidates-list-item-title">
                        <h2><%= link_to resume.user.name, resume %></a></h2>
                        <h3><%= resume.category %></h3>
                    </div><!-- /.candidates-list-item-title -->
                </div><!-- /.candidates-list-item-heading -->

                    <div class="candidates-list-item-location">
                        <i class="fa fa-map-marker"></i> <%= resume.address %>
                    </div><!-- /.candidates-list-item-location -->

                <div class="candidates-list-item-profile">
                    <span class="candidates-list-item-profile-count">92% completed</span>
                	<span class="candidates-list-item-profile-bar"><span style="width: 92%"></span></span>
                                   
                </div><!-- /.candidates-list-item-rating -->    		
        	</div><!-- /.candidates-list-item -->
            <% end %> 	
            </div><!-- /.containert -->
        </div>
    </div>
</div>

app/views/resumes/new.html.erb
<div class="container">
        <div class="col-sm-12">
	       <h4 class ="center">Create Your Resume</h4>
        </div>
    <div class="col-sm-8">
			<%= form_for @resume do |f| %>
    	<div class= "row">
            
    		<div class="col-sm-5">
    			<div class="form-group">
    				<%= f.label :age %><span> Date of birth</span>
    				<%= f.date_field :age, max: Date.today - 5475, autofocus: true, class: "form-control input-lg" %>
    			</div><!-- /.form-group -->
    		</div> 
    		<div class="col-sm-5">
    			<div class="form-group">
    				<%= f.label :phone %><span> Active Mobile number</span>
    				<%= f.text_field :phone, class: "form-control input-lg" %>
    			</div><!-- /.form-group -->
    		</div>
            <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :Address %><span> Where do you live currently</span>
                    <%= f.text_field :address, autofocus: true, class: "form-control input-lg" %>
                </div><!-- /.form-group -->
            </div>

             <div class="col-sm-10">
                <div class="form-group">
                    <%= f.label :category %> <span> Business Category you're interested in</span>
                    <%= f.text_field :category, autofocus: true, class: "form-control input-lg" %>
                </div><!-- /.form-group -->
            </div>
    		<div class="col-sm-10">
    			<div class="form-group">
    				<%= f.label :bio %><span> Your bio, Be conscise (280 xters)</span>
    				<%= f.text_area :bio, class: "form-control" %>
    			</div><!-- /.form-group -->
    		</div>

    		
            </div>
    		<div class="col-sm-3">
	  			<div class="form-group">
	             <%= f.submit "Next", class: "btn btn-secondary btn-block" %>
	            </div>
        	</div>
	</div>
		<% end %>

    <div class="col-sm-4">
        <div class="widget">
            <h2>Tips :</h2>
            <ul class="nav">
                <li><span>1.</span> Enter full names </li>
                <li><span>2.</span> Date of birth (calculates age)</li>
                <li><span>3.</span> Phone (hidden to the public)</li>
            </ul>
        </div><!-- /.widget --> 
        <div class="widget">
            <h2>Your Bio</h2>
            <p>Start your bio with "I'm a student at ABC School and I am looking for internship in (category), I'm hardworking etc" </p>

        </div><!-- /.widget -->   
    </div><!-- /.col-* -->

</div><!-- /.col-* -->

app/views/resumes/show.html.erb
            <div class="container">
    <div class="resume">
    <div class="resume-main">
        <div class="resume-main-image">

        </div><!-- /.resume-main-image -->

        <div class="resume-main-content">
            <h2><%= @resume.user.name %>
                <!-- <span class="resume-main-verified">v<i class="fa fa-check"></i></span> -->
            </h2>

            <h3><%= @resume.category %></h3><br>
            <small class="resume-main-contacts">
                 Phone <%= @resume.phone %> | Email: <%= current_user.email %> | From: <%= @resume.address %>
            </small><br>
            <span class="companies-list-item-rating-count"><%= link_to "Delete this resume", @resume, method: :delete, data: { confirm: 'Are you sure? this will destory the resume completely' } %></span> 
         <!-- <div class="resume-main-actions">
                <a href="#" class="btn btn-secondary"><i class="fa fa-download"></i> Download</a>
                <a href="#" class="btn btn-default">Contact</a>
                <a href="#" class="btn btn-default">Follow</a>
            </div>  --><!-- /.resume-main-actions -->
        </div><!-- /.resume-main-content -->
    </div><!-- /.resume-main -->

    <div class="resume-chapter">
        <div class="resume-chapter-inner">
            <div class="resume-chapter-title">
                <h2>Summary</h2>
            </div><!-- /.resume-chapter-title -->

            <div class="resume-chapter-content">
                <p>
                    <%= @resume.bio %>
                </p>

            </div><!-- /.resume-chapter-content -->
        </div><!-- /.resume-chapter-inner -->
    </div><!-- /.resume-chapter -->
    <div class="resume-chapter">
        <div class="resume-chapter-inner">
            <div class="resume-chapter-content">
                <h2 class="mb40">Experience: <span> 
                    <%= link_to "Add",  new_resume_job_path(@resume), class: "btn btn-secondary" %></span></h2>

                <dl>
                    <% @jobs.each do |job| %>

                    <dt><%= job.sdate.strftime ("%Y") %> - <%= job.edate.strftime ("%Y") %> </dt>
                    <dd>
                        <Strong><%= job.cname %></Strong><br>
                        <i class="small"><%= job.role %></i>
                        <p><%= job.description %></p>
                    </dd>
                    <% end %>      
                </dl>
            </div><!-- /.resume-chapter-content -->
        </div><!-- /.resume-chapter-inner -->
    </div><!-- /.resume-chapter -->
    <div class="resume-chapter">
        <div class="resume-chapter-inner">
            <div class="resume-chapter-content">
                <h2 class="mb40">Education: <span> <%= link_to "Add",  new_resume_edu_path(@resume), class: "btn btn-secondary" %></span></h2>

                <dl>
                    <% @edus.each do |edu| %>

                    <dt><%= edu.sdate.strftime ("%Y") %> - <%= edu.edate.strftime ("%Y") %> </dt>
                    <dd>
                        <Strong><%= edu.sname %></Strong><br>
                        <i class="small"><%= edu.course %></i>
                        <p><%= edu.description %></p>
                    </dd>
                    <% end %>      
                </dl>
            </div><!-- /.resume-chapter-content -->
        </div><!-- /.resume-chapter-inner -->
    </div><!-- /.resume-chapter -->
 <div class="resume-chapter">
        <div class="resume-chapter-inner">
            <div class="resume-chapter-content">
                <h2 class="mb40">Skills: <span> <%= link_to "Add",  new_resume_skill_path(@resume), class: "btn btn-secondary" %></span></h2>

                <dl>
                    
                    <% @skills.each do |skill| %>
                    <dt>Skills and Hobbies </dt>
                    <dd>
                        <p><%= skill.name %></p>
                    </dd>
                    <% end %>      
                </dl>
            </div><!-- /.resume-chapter-content -->
        </div><!-- /.resume-chapter-inner -->
    </div><!-- /.resume-chapter -->
        </div><!-- /.resume-chapter-inner -->
</div><!-- /.resume -->

</div><!-- /.container -->