config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  	resources :dashboard

	resources :companies do
		resources	:gigs do
			resource :proposals, except: :index
		end
		# resources	:proposals
	end
	resources	:gigs
	# Manage links to interns, resumes
	resources :resumes do
		resources :edus
		resources :jobs
		resources :skills

	end
 
 # if user_signed_in? && current_user.is_employer?
		root 'gigs#index'
	# else 
		root 'gig#resumes'
	# end
		get 'listing' => "companies#listing"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
	belongs_to	:gig
	belongs_to	:skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many	:gigs
	
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many	:categories
	has_many	:gigs
	belongs_to	:user
end

app/models/edu.rb
class Edu < ApplicationRecord
     belongs_to	:resume
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	belongs_to	:company
	has_many	:proposals
	belongs_to 	:category
	has_many	:abilities
	has_many	:skills, through: :abilities

	validates :name, :description, :budget, :startdate, :duration, presence: true

	def skill_list=(skills_string)
		skill_names = skills_string.split(",").collect{ |s| s.strip.downcase}.uniq
		new_or_found_skills = skill_names.collect { |name| Skill.find_or_create_by(name: name) }
		self.skills = new_or_found_skills
	end

	def skill_list
		self.skills.collect do |skill|
			skill.name
		end.join(",")
	end
end

app/models/job.rb
class Job < ApplicationRecord
     belongs_to	:resume
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many	:skills
	#belongs_to	:user
	#belongs_to :category
	has_many	:abilities
	has_many	:skills, through: :abilities
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	belongs_to 	:gig
	belongs_to	:user
	# belongs_to :resume
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	#belongs_to :category
	has_many :proposals
	belongs_to	:user 
	has_many	:edus
	has_many	:jobs
	has_many	:skills
	has_many	:abilities
	has_many	:skills, through: :abilities
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many	:abilities
	has_many	:gigs, through: :abilities
	belongs_to :resume, optional: true


	# def skill_list=(skills_string)
	# 	skill_names = skills_string.split(",").collect{ |s| s.strip.downcase}.uniq
	# 	new_or_found_skills = skill_names.collect { |name| Skill.find_or_create_by(name: name) }
	# 	self.skills = new_or_found_skills
	# end

	# def skill_list
	# 	self.skills.collect do |skill|
	# 		skill.name
	# 	end.join(",")
	# end
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        has_many	:gigs
        has_many	:proposals
        has_many	:edus
        has_many	:resumes
        has_many	:companies
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :set_company, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index]

def listing
	@company = Company.where(user_id: current_user.id)
	@gigs = Gig.all
end

def index
	@company = Company.all
	@gig = Gig.all.order("created_at DESC")
end

def new
	@company = Company.new
end

def create
	@company = Company.new (company_params)
	@company.user_id = current_user.id
	@company.save!
	redirect_to @company	
end

def show
	@gigs = Gig.where(company_id: @company.id).order("created_at DESC")
end

def edit
	
end

def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
	@company.destroy
	redirect_to @company
end


private 


	def company_params
		params.require(:company).permit(:cname, :industry, :email, :website, :location, :description)
	end

	def check_user
      unless (@company.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this company belongs to someone else, you can only edit companies you have posted."
      end
    end

	def set_company
		@company = Company.find_by(:id => params[:id])	
	end


end

app/controllers/edus_controller.rb
class EdusController < ApplicationController
	before_action :set_resume

	def index
		@edu = Edu.all
	end

	def new
		@edu = Edu.new
	end

	def create
		@edu = Edu.new(edu_params)
		@edu.resume_id = @resume.id
		@edu.save!
		redirect_to @resume	
	end

	def show
		@edu = Edu.find(params[:id])
	end

private

	def set_resume
		@resume = Resume.find(params[:resume_id])	
	end

	def edu_params
		params.require(:edu).permit(:sname, :sdate, :edate, :course, :description)
	end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
	 before_action :set_company, except: [:index, :show, :update]
	 before_action :set_gig, only: [:show, :edit, :update, :destroy]
	 # before_action :authenticate_user!, except: [:index]

	def index
		@gig = Gig.all
	end

	def new
		@gig = Gig.new 
	end

	def create
		@gig = Gig.new(gig_params)
		@gig.company_id = @company.id
		@gig.save!
		redirect_to @company
	end

	def show
		@gig = Gig.find(params[:id])
		@company = Company.where(gig_id: @gig.id)
		@proposal = @gig.proposals.order("created_at DESC")
		# @resume = @user.resumes.order("created_at DESC")
		@resume = Resume.all
		#@resumes = Resume.where(user_id: @user.id).order("created_at DESC")
		@awarded_internship = Proposal.where(id: @gig.awarded_internship).first
	end


	def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

	def destroy
		@gig.destroy
		redirect_to company_path(@company)
	end


	
#private stuff
	private

	def set_company
		@company = Company.find(params[:company_id])	
	end

	def set_gig
		@gig = Gig.find_by(:id => params[:id])
	end

	def gig_params
		params.require(:gig).permit(:name, :description, :budget, :startdate, :duration, :location, :category_id, :skill_list, :awarded_internship)
	end




end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_resume

	def index
		@job = Job.all
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)
		@job.resume_id = @resume.id
		@job.save!
		redirect_to @resume	
	end

	def show
		@job = Job.find(params[:id])
	end

private

	def set_resume
		@resume = Resume.find(params[:resume_id])	
	end

	def job_params
		params.require(:job).permit(:cname, :role, :sdate, :edate, :description)
	end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	before_action :set_resume, only: [:index, :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		@resume = Resume.all
	end

	def new
		@resume = Resume.new	
	end

	def create
		@resume = Resume.new (resume_params)
		@resume.user_id = current_user.id
		@resume.save!
		redirect_to @resume
	end

	def show
		@resume = Resume.find(params[:id])
		@jobs = Job.where(resume_id: @resume.id)
		@edus = Edu.where(resume_id: @resume.id)
		@skills = Skill.where(resume_id: @resume.id)

	end

	def destroy
		@resume.destroy
		redirect_to @resume	
	end

private

	def resume_params
		params.require(:resume).permit(:fname, :lname, :age, :phone, :address, :category, :bio)
	end

	def set_resume
		
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	before_action :set_resume

	def index
		@skill = Skill.all
	end

	def new
		@skill = Skill.new
	end

	def create
		@skill = Skill.new(skill_params)
		@skill.resume_id = @resume.id
		@skill.save!
		redirect_to @resume	
	end

	def show
		@skill = Skill.find(params[:id])
	end

private

	def set_resume
		@resume = Resume.find(params[:resume_id])	
	end

	def skill_params
		params.require(:skill).permit(:name)
	end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController

		

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
    <!--<div class="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="footer-top-block">
                            <h2><i class="profession profession-logo"></i> Ma:Interns</h2>

                            <p>
                                Find the right interns for your company with ma:interns. It's that simple
                            </p>

                            <ul class="social-links">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-sm-3 col-sm-offset-1">
                        <div class="footer-top-block">
                            <h2>Helpful Links</h2>

                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="pricing.html">Pricing</a></li>
                                <li><a href="#">Terms &amp; Conditions</a></li>
                                <li><a href="#">Support/Contact</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="footer-top-block">
                            <h2>Trending Jobs</h2>

                            <ul>
                                <li><a href="position-detail.html">Data Entry</a></li>
                                <li><a href="position-detail.html">Writer</a></li>
                            </ul>
                        </div><!-- /.footer-top-left -->
                    </div><!-- /.col-* -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.footer-top -->

        <div class="footer-bottom">
            <div class="container">
                <div class="footer-bottom-left">
                    &copy; <a href="#">Ma:Interns</a>, 2017 All rights reserved.
                </div><!-- /.footer-bottom-left -->

                <!--<div class="footer-bottom-right">
                    Sponsored by <a href="http://www.kuhustle.com">Kuhustle</a>  and <a href="http://www.nailab.co.ke">Nailab</a> 
                </div><!-- /.footer-bottom-right -->
            </div><!-- /.container -->
        </div><!-- /.footer-bottom -->
    </div><!-- /.footer -->

app/views/layouts/_nav.html.erb
<div class="page-wrapper">
<div class="header-wrapper">
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="header-brand">
                    <div class="header-logo">
               
                        <i class="profession profession-logo"></i>
                         <% if user_signed_in? && current_user.is_employer? %>

                        <span class="header-logo-text"><%= link_to "Ma", root_path %> <span class="header-logo-highlight">:</span><%= link_to "Interns", root_path %></span>

                      <% else %>

                        <span class="header-logo-text"><%= link_to "Ma", root_path %> <span class="header-logo-highlight">:</span><%= link_to "Interns", root_path %></span>
                        <% end %>
                    </div><!-- /.header-logo-->

                    <div class="header-slogan">
                        <span class="header-slogan-slash">/</span>
                        <span class="header-slogan-text">Attachment job Portal </span>
                    </div><!-- /.header-slogan-->
                </div><!-- /.header-brand -->

                <ul class="header-actions nav nav-pills">

                    <!--if user wants to post an internship, is user logged in? ask to log in, has User created a company? if not ask to create a company, if user has created a company, allow to create an internship under that company, user can create multiple companies and multiple internships under the company -->
                   


                <% if user_signed_in? && current_user.is_employer? %>
                  <li><%= link_to "Find Interns", resumes_path, class: "primary" %></li> 
                  <li><%= link_to "Dashboard: Post Job &raquo".html_safe, listing_path, class: "primary" %>
                <% elsif user_signed_in? %>
                  <li><%= link_to "Find Internship".html_safe, gigs_path, class: "primary" %>
                  <li><%= link_to "Companies hiring", companies_path, class: "primary" %></li> 
                <% else %>
                  <li><%= link_to "Find Interns", resumes_path, class: "primary" %></li> 
                  <li><%= link_to "Post Internship Opportunity".html_safe, listing_path, class: "primary" %></li> 
                <% end %>      
                  
                 
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <% if user_signed_in? %> 
                          <%= current_user.name %>  <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                            <% else %>
                             <li><%= link_to "Login in", new_user_session_path %></li>
                             <li><%= link_to "Sign Up", new_user_registration_path %></li>
                             <li role="separator" class="divider"></li>
                            <% end %> 
                          </ul>
                      </li>
                </ul><!-- /.header-actions -->

                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".header-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div><!-- /.container -->
              </div>
        <!-- /.header-top -->
    </div><!-- /.header -->
</div><!-- /.header-wrapper-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intern</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/nav'%>

    <%= yield %>
     <%= render 'layouts/footer'%>
  </body>
</html>